feat: v2 removes the PREFIX variable
It proved unhelpful to force the clone directory to match the name of the prefix by default.

And it is significantly simpler without that affordance

diff --git a/Taskfile_test.yml b/Taskfile_test.yml
--- a/Taskfile_test.yml
+++ b/Taskfile_test.yml
@@ -1,7 +1,8 @@
-version: '3'
+version: "3"
 vars:
   CURL_SH: $(curl -fsSL https://raw.githubusercontent.com/robinbryce/git-bootstrap/refs/heads/main/git-bootstrap.sh)
   LOCAL_SH: $(cat {{.TASKFILE_DIR}}/git-bootstrap.sh)
+  V2_LOCAL_SH: $(cat {{.TASKFILE_DIR}}/git-bootstrap.v2.sh)
 tasks:
   default:
     - task: parse_checkout
@@ -16,21 +17,71 @@ tasks:
           - "git@github.com:latticexyz/mud.git@create-mud@2.2.14 CHECKOUT mud create-mud@2.2.14"
           - "git@github.com:latticexyz/mud.git#foo@create-mud@2.2.14 CHECKOUT foo create-mud@2.2.14"
           # default directory with no tag or branch
-          -  "git@github.com:latticexyz/mud.git NOOP git@github.com:latticexyz/mud.git"
+          - "git@github.com:latticexyz/mud.git NOOP git@github.com:latticexyz/mud.git"
           # directory with no tag or branch
           - "git@github.com:latticexyz/mud.git#foo NOOP git@github.com:latticexyz/mud.git#foo"
         cmd: |
-            case="{{.ITEM}}"
-            input="${case%% *}"
-            expect="${case#* }"
-            # echo "input=$input; expect=$expect"
-            got=$(sh -c "{{.LOCAL_SH}}" - parse_checkout "$input")
-            if [[ "$got" != "$expect" ]]; then
-              echo "FAIL: $input => \"$got\", expected \"$expect\""
-              exit 1
-            fi
-            got=$(sh -c "{{.CURL_SH}}" - parse_checkout "$input")
-            if [[ "$got" != "$expect" ]]; then
-              echo "FAIL: (remote) $input => \"$got\", expected \"$expect\""
-              exit 1
-            fi
+          case="{{.ITEM}}"
+          input="${case%% *}"
+          expect="${case#* }"
+          # echo "input=$input; expect=$expect"
+          got=$(sh -c "{{.LOCAL_SH}}" - parse_checkout "$input")
+          if [[ "$got" != "$expect" ]]; then
+            echo "FAIL: $input => \"$got\", expected \"$expect\""
+            exit 1
+          fi
+          got=$(sh -c "{{.CURL_SH}}" - parse_checkout "$input")
+          if [[ "$got" != "$expect" ]]; then
+            echo "FAIL: (remote) $input => \"$got\", expected \"$expect\""
+            exit 1
+          fi
+
+  parse_checkout:v2:local:
+    desc: test parse_checkout
+    cmds:
+      - for:
+          - "git@github.com:latticexyz/mud.git@v.1.2.3 CHECKOUT mud v.1.2.3"
+          - "git@github.com:latticexyz/mud.git#foo@v.1.2.3 CHECKOUT foo v.1.2.3"
+          - "git@github.com:latticexyz/mud.git^bar CHECKOUT mud bar"
+          - "git@github.com:latticexyz/mud.git#foo^bar CHECKOUT foo bar"
+          - "git@github.com:latticexyz/mud.git@create-mud@2.2.14 CHECKOUT mud create-mud@2.2.14"
+          - "git@github.com:latticexyz/mud.git#foo@create-mud@2.2.14 CHECKOUT foo create-mud@2.2.14"
+          # default directory with no tag or branch
+          - "git@github.com:latticexyz/mud.git NOOP git@github.com:latticexyz/mud.git"
+          # directory with no tag or branch
+          - "git@github.com:latticexyz/mud.git#foo NOOP git@github.com:latticexyz/mud.git#foo"
+        cmd: |
+          case="{{.ITEM}}"
+          input="${case%% *}"
+          expect="${case#* }"
+          # echo "input=$input; expect=$expect"
+          got=$(sh -c "{{.V2_LOCAL_SH}}" - parse_checkout "$input")
+          if [[ "$got" != "$expect" ]]; then
+            echo "FAIL: $input => \"$got\", expected \"$expect\""
+            exit 1
+          fi
+
+  parse_checkout:v2:curl:
+    desc: test parse_checkout
+    cmds:
+      - for:
+          - "git@github.com:latticexyz/mud.git@v.1.2.3 CHECKOUT mud v.1.2.3"
+          - "git@github.com:latticexyz/mud.git#foo@v.1.2.3 CHECKOUT foo v.1.2.3"
+          - "git@github.com:latticexyz/mud.git^bar CHECKOUT mud bar"
+          - "git@github.com:latticexyz/mud.git#foo^bar CHECKOUT foo bar"
+          - "git@github.com:latticexyz/mud.git@create-mud@2.2.14 CHECKOUT mud create-mud@2.2.14"
+          - "git@github.com:latticexyz/mud.git#foo@create-mud@2.2.14 CHECKOUT foo create-mud@2.2.14"
+          # default directory with no tag or branch
+          - "git@github.com:latticexyz/mud.git NOOP git@github.com:latticexyz/mud.git"
+          # directory with no tag or branch
+          - "git@github.com:latticexyz/mud.git#foo NOOP git@github.com:latticexyz/mud.git#foo"
+        cmd: |
+          case="{{.ITEM}}"
+          input="${case%% *}"
+          expect="${case#* }"
+          # echo "input=$input; expect=$expect"
+          got=$(sh -c "{{.V2_CURL_SH}}" - parse_checkout "$input")
+          if [[ "$got" != "$expect" ]]; then
+            echo "FAIL: $input => \"$got\", expected \"$expect\""
+            exit 1
+          fi
